title: Gyubin's learning
email: geubin0414@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  1. 오늘보다 조금 더 발전한 내일이 되자.<br>
  2. 중요한 것은 포기하지 않는 것.<br>
  &nbsp; &nbsp; 더딘 것을 염려하지 말고, 멈출 것을 염려하자.<br>
  3. 공부 슬럼프는 공부로 극복한다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gyubin.github.io/" # the base hostname & protocol for your site
twitter_username: geubin0414
github_username:  gyubin

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

#permalink
permalink: pretty
